package com.jac.travels.model;

import com.datastax.driver.core.LocalDate;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

import java.time.ZonedDateTime;

@Table("room_allocation")
public class RoomAllocation {
    @PrimaryKey
    private	Integer	room_id	;
    @PrimaryKey
    private LocalDate stay_date	;
    private	Integer	allocation	;
    private	Boolean	child_close_out	;
    private	Boolean	child_youth_close_out	;
    private	Boolean	close_out	;
    private	Integer	extra_bed_allocation	;
    private	Integer	extra_bed_sold	;
    private	Boolean	is_free_sale	;
    private	Integer	max_duration	;
    private	Integer	min_allocation	;
    private	Integer	min_duration	;
    private	Integer	occupancy01_allocation	;
    private	Integer	occupancy01_sold	;
    private	Integer	occupancy02_allocation	;
    private	Integer	occupancy02_sold	;
    private	Integer	occupancy03_allocation	;
    private	Integer	occupancy03_sold	;
    private	Integer	occupancy04_allocation	;
    private	Integer	occupancy04_sold	;
    private	Integer	occupancy05_allocation	;
    private	Integer	occupancy05_sold	;
    private	Integer	occupancy06_allocation	;
    private	Integer	occupancy06_sold	;
    private	Integer	occupancy07_allocation	;
    private	Integer	occupancy07_sold	;
    private	Integer	occupancy08_allocation	;
    private	Integer	occupancy08_sold	;
    private	Integer	occupancy09_allocation	;
    private	Integer	occupancy09_sold	;
    private	Integer	occupancy10_allocation	;
    private	Integer	occupancy10_sold	;
    private	Integer	occupancy11_allocation	;
    private	Integer	occupancy11_sold	;
    private	Integer	occupancy12_allocation	;
    private	Integer	occupancy12_sold	;
    private	Integer	occupancy13_allocation	;
    private	Integer	occupancy13_sold	;
    private	Integer	occupancy14_allocation	;
    private	Integer	occupancy14_sold	;
    private	Integer	occupancy15_allocation	;
    private	Integer	occupancy15_sold	;
    private	Integer	occupancy16_allocation	;
    private	Integer	occupancy16_sold	;
    private	Integer	occupancy17_allocation	;
    private	Integer	occupancy17_sold	;
    private	Integer	occupancy18_allocation	;
    private	Integer	occupancy18_sold	;
    private	Integer	occupancy19_allocation	;
    private	Integer	occupancy19_sold	;
    private	Integer	occupancy20_allocation	;
    private	Integer	occupancy20_sold	;
    private	Integer	occupancy21_allocation	;
    private	Integer	occupancy21_sold	;
    private	Integer	occupancy22_allocation	;
    private	Integer	occupancy22_sold	;
    private	Integer	occupancy23_allocation	;
    private	Integer	occupancy23_sold	;
    private	Integer	occupancy24_allocation	;
    private	Integer	occupancy24_sold	;
    private	Integer	occupancy25_allocation	;
    private	Integer	occupancy25_sold	;
    private	Integer	occupancy26_allocation	;
    private	Integer	occupancy26_sold	;
    private	Integer	occupancy27_allocation	;
    private	Integer	occupancy27_sold	;
    private	Integer	occupancy28_allocation	;
    private	Integer	occupancy28_sold	;
    private	Integer	occupancy29_allocation	;
    private	Integer	occupancy29_sold	;
    private	Integer	occupancy30_allocation	;
    private	Integer	occupancy30_sold	;
    private	Integer	occupancy31_allocation	;
    private	Integer	occupancy31_sold	;
    private	Integer	occupancy32_allocation	;
    private	Integer	occupancy32_sold	;
    private	Integer	occupancy33_allocation	;
    private	Integer	occupancy33_sold	;
    private	Integer	occupancy34_allocation	;
    private	Integer	occupancy34_sold	;
    private	Integer	occupancy35_allocation	;
    private	Integer	occupancy35_sold	;
    private	Integer	occupancy36_allocation	;
    private	Integer	occupancy36_sold	;
    private	Integer	occupancy37_allocation	;
    private	Integer	occupancy37_sold	;
    private	Integer	occupancy38_allocation	;
    private	Integer	occupancy38_sold	;
    private	Integer	occupancy39_allocation	;
    private	Integer	occupancy39_sold	;
    private	Integer	occupancy40_allocation	;
    private	Integer	occupancy40_sold	;
    private	Integer	occupancy41_allocation	;
    private	Integer	occupancy41_sold	;
    private	Integer	occupancy42_allocation	;
    private	Integer	occupancy42_sold	;
    private	Integer	occupancy43_allocation	;
    private	Integer	occupancy43_sold	;
    private	Integer	occupancy44_allocation	;
    private	Integer	occupancy44_sold	;
    private	Integer	occupancy45_allocation	;
    private	Integer	occupancy45_sold	;
    private	Integer	occupancy46_allocation	;
    private	Integer	occupancy46_sold	;
    private	Integer	occupancy47_allocation	;
    private	Integer	occupancy47_sold	;
    private	Integer	occupancy48_allocation	;
    private	Integer	occupancy48_sold	;
    private	Integer	occupancy49_allocation	;
    private	Integer	occupancy49_sold	;
    private	Integer	occupancy50_allocation	;
    private	Integer	occupancy50_sold	;
    private	Integer	release	;
    private	Integer	sold	;
    private	Integer	split_release	;
    private	Integer	split_release_allocation	;
    private	Integer	split_release_sold	;
    private	Integer	total_sold	;
    private ZonedDateTime utc_release_date_time	;
    private	ZonedDateTime	utc_split_release_date_time	;

}
