// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/contract.proto

package com.jac.travels.protobuf;

public final class Contract {
  private Contract() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContractRequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jac.travels.protobuf.ContractRequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 propertyId = 10;</code>
     */
    int getPropertyId();

    /**
     * <code>int32 contractId = 20;</code>
     */
    int getContractId();

    /**
     * <code>string bookingFrom = 30;</code>
     */
    java.lang.String getBookingFrom();
    /**
     * <code>string bookingFrom = 30;</code>
     */
    com.google.protobuf.ByteString
        getBookingFromBytes();

    /**
     * <code>string booking_to = 40;</code>
     */
    java.lang.String getBookingTo();
    /**
     * <code>string booking_to = 40;</code>
     */
    com.google.protobuf.ByteString
        getBookingToBytes();

    /**
     * <code>string buying_currency = 50;</code>
     */
    java.lang.String getBuyingCurrency();
    /**
     * <code>string buying_currency = 50;</code>
     */
    com.google.protobuf.ByteString
        getBuyingCurrencyBytes();

    /**
     * <code>int32 channel_manager_id = 60;</code>
     */
    int getChannelManagerId();

    /**
     * <code>int32 channel_type_id = 70;</code>
     */
    int getChannelTypeId();

    /**
     * <code>int32 contract_status_id = 80;</code>
     */
    int getContractStatusId();

    /**
     * <code>int32 contract_type_id = 90;</code>
     */
    int getContractTypeId();

    /**
     * <code>int32 follow_on_contract_id = 100;</code>
     */
    int getFollowOnContractId();

    /**
     * <code>int32 no_end_dates = 110;</code>
     */
    int getNoEndDates();

    /**
     * <code>string stay_from = 120;</code>
     */
    java.lang.String getStayFrom();
    /**
     * <code>string stay_from = 120;</code>
     */
    com.google.protobuf.ByteString
        getStayFromBytes();

    /**
     * <code>string stay_to = 130;</code>
     */
    java.lang.String getStayTo();
    /**
     * <code>string stay_to = 130;</code>
     */
    com.google.protobuf.ByteString
        getStayToBytes();
  }
  /**
   * Protobuf type {@code com.jac.travels.protobuf.ContractRequestProto}
   */
  public  static final class ContractRequestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jac.travels.protobuf.ContractRequestProto)
      ContractRequestProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContractRequestProto.newBuilder() to construct.
    private ContractRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContractRequestProto() {
      propertyId_ = 0;
      contractId_ = 0;
      bookingFrom_ = "";
      bookingTo_ = "";
      buyingCurrency_ = "";
      channelManagerId_ = 0;
      channelTypeId_ = 0;
      contractStatusId_ = 0;
      contractTypeId_ = 0;
      followOnContractId_ = 0;
      noEndDates_ = 0;
      stayFrom_ = "";
      stayTo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContractRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 80: {

              propertyId_ = input.readInt32();
              break;
            }
            case 160: {

              contractId_ = input.readInt32();
              break;
            }
            case 242: {
              java.lang.String s = input.readStringRequireUtf8();

              bookingFrom_ = s;
              break;
            }
            case 322: {
              java.lang.String s = input.readStringRequireUtf8();

              bookingTo_ = s;
              break;
            }
            case 402: {
              java.lang.String s = input.readStringRequireUtf8();

              buyingCurrency_ = s;
              break;
            }
            case 480: {

              channelManagerId_ = input.readInt32();
              break;
            }
            case 560: {

              channelTypeId_ = input.readInt32();
              break;
            }
            case 640: {

              contractStatusId_ = input.readInt32();
              break;
            }
            case 720: {

              contractTypeId_ = input.readInt32();
              break;
            }
            case 800: {

              followOnContractId_ = input.readInt32();
              break;
            }
            case 880: {

              noEndDates_ = input.readInt32();
              break;
            }
            case 962: {
              java.lang.String s = input.readStringRequireUtf8();

              stayFrom_ = s;
              break;
            }
            case 1042: {
              java.lang.String s = input.readStringRequireUtf8();

              stayTo_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jac.travels.protobuf.Contract.internal_static_com_jac_travels_protobuf_ContractRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jac.travels.protobuf.Contract.internal_static_com_jac_travels_protobuf_ContractRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jac.travels.protobuf.Contract.ContractRequestProto.class, com.jac.travels.protobuf.Contract.ContractRequestProto.Builder.class);
    }

    public static final int PROPERTYID_FIELD_NUMBER = 10;
    private int propertyId_;
    /**
     * <code>int32 propertyId = 10;</code>
     */
    public int getPropertyId() {
      return propertyId_;
    }

    public static final int CONTRACTID_FIELD_NUMBER = 20;
    private int contractId_;
    /**
     * <code>int32 contractId = 20;</code>
     */
    public int getContractId() {
      return contractId_;
    }

    public static final int BOOKINGFROM_FIELD_NUMBER = 30;
    private volatile java.lang.Object bookingFrom_;
    /**
     * <code>string bookingFrom = 30;</code>
     */
    public java.lang.String getBookingFrom() {
      java.lang.Object ref = bookingFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookingFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string bookingFrom = 30;</code>
     */
    public com.google.protobuf.ByteString
        getBookingFromBytes() {
      java.lang.Object ref = bookingFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookingFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOKING_TO_FIELD_NUMBER = 40;
    private volatile java.lang.Object bookingTo_;
    /**
     * <code>string booking_to = 40;</code>
     */
    public java.lang.String getBookingTo() {
      java.lang.Object ref = bookingTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookingTo_ = s;
        return s;
      }
    }
    /**
     * <code>string booking_to = 40;</code>
     */
    public com.google.protobuf.ByteString
        getBookingToBytes() {
      java.lang.Object ref = bookingTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookingTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUYING_CURRENCY_FIELD_NUMBER = 50;
    private volatile java.lang.Object buyingCurrency_;
    /**
     * <code>string buying_currency = 50;</code>
     */
    public java.lang.String getBuyingCurrency() {
      java.lang.Object ref = buyingCurrency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buyingCurrency_ = s;
        return s;
      }
    }
    /**
     * <code>string buying_currency = 50;</code>
     */
    public com.google.protobuf.ByteString
        getBuyingCurrencyBytes() {
      java.lang.Object ref = buyingCurrency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buyingCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_MANAGER_ID_FIELD_NUMBER = 60;
    private int channelManagerId_;
    /**
     * <code>int32 channel_manager_id = 60;</code>
     */
    public int getChannelManagerId() {
      return channelManagerId_;
    }

    public static final int CHANNEL_TYPE_ID_FIELD_NUMBER = 70;
    private int channelTypeId_;
    /**
     * <code>int32 channel_type_id = 70;</code>
     */
    public int getChannelTypeId() {
      return channelTypeId_;
    }

    public static final int CONTRACT_STATUS_ID_FIELD_NUMBER = 80;
    private int contractStatusId_;
    /**
     * <code>int32 contract_status_id = 80;</code>
     */
    public int getContractStatusId() {
      return contractStatusId_;
    }

    public static final int CONTRACT_TYPE_ID_FIELD_NUMBER = 90;
    private int contractTypeId_;
    /**
     * <code>int32 contract_type_id = 90;</code>
     */
    public int getContractTypeId() {
      return contractTypeId_;
    }

    public static final int FOLLOW_ON_CONTRACT_ID_FIELD_NUMBER = 100;
    private int followOnContractId_;
    /**
     * <code>int32 follow_on_contract_id = 100;</code>
     */
    public int getFollowOnContractId() {
      return followOnContractId_;
    }

    public static final int NO_END_DATES_FIELD_NUMBER = 110;
    private int noEndDates_;
    /**
     * <code>int32 no_end_dates = 110;</code>
     */
    public int getNoEndDates() {
      return noEndDates_;
    }

    public static final int STAY_FROM_FIELD_NUMBER = 120;
    private volatile java.lang.Object stayFrom_;
    /**
     * <code>string stay_from = 120;</code>
     */
    public java.lang.String getStayFrom() {
      java.lang.Object ref = stayFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stayFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string stay_from = 120;</code>
     */
    public com.google.protobuf.ByteString
        getStayFromBytes() {
      java.lang.Object ref = stayFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stayFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STAY_TO_FIELD_NUMBER = 130;
    private volatile java.lang.Object stayTo_;
    /**
     * <code>string stay_to = 130;</code>
     */
    public java.lang.String getStayTo() {
      java.lang.Object ref = stayTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stayTo_ = s;
        return s;
      }
    }
    /**
     * <code>string stay_to = 130;</code>
     */
    public com.google.protobuf.ByteString
        getStayToBytes() {
      java.lang.Object ref = stayTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stayTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (propertyId_ != 0) {
        output.writeInt32(10, propertyId_);
      }
      if (contractId_ != 0) {
        output.writeInt32(20, contractId_);
      }
      if (!getBookingFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 30, bookingFrom_);
      }
      if (!getBookingToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 40, bookingTo_);
      }
      if (!getBuyingCurrencyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 50, buyingCurrency_);
      }
      if (channelManagerId_ != 0) {
        output.writeInt32(60, channelManagerId_);
      }
      if (channelTypeId_ != 0) {
        output.writeInt32(70, channelTypeId_);
      }
      if (contractStatusId_ != 0) {
        output.writeInt32(80, contractStatusId_);
      }
      if (contractTypeId_ != 0) {
        output.writeInt32(90, contractTypeId_);
      }
      if (followOnContractId_ != 0) {
        output.writeInt32(100, followOnContractId_);
      }
      if (noEndDates_ != 0) {
        output.writeInt32(110, noEndDates_);
      }
      if (!getStayFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 120, stayFrom_);
      }
      if (!getStayToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 130, stayTo_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (propertyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, propertyId_);
      }
      if (contractId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, contractId_);
      }
      if (!getBookingFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(30, bookingFrom_);
      }
      if (!getBookingToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(40, bookingTo_);
      }
      if (!getBuyingCurrencyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(50, buyingCurrency_);
      }
      if (channelManagerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(60, channelManagerId_);
      }
      if (channelTypeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(70, channelTypeId_);
      }
      if (contractStatusId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(80, contractStatusId_);
      }
      if (contractTypeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(90, contractTypeId_);
      }
      if (followOnContractId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(100, followOnContractId_);
      }
      if (noEndDates_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(110, noEndDates_);
      }
      if (!getStayFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(120, stayFrom_);
      }
      if (!getStayToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(130, stayTo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jac.travels.protobuf.Contract.ContractRequestProto)) {
        return super.equals(obj);
      }
      com.jac.travels.protobuf.Contract.ContractRequestProto other = (com.jac.travels.protobuf.Contract.ContractRequestProto) obj;

      boolean result = true;
      result = result && (getPropertyId()
          == other.getPropertyId());
      result = result && (getContractId()
          == other.getContractId());
      result = result && getBookingFrom()
          .equals(other.getBookingFrom());
      result = result && getBookingTo()
          .equals(other.getBookingTo());
      result = result && getBuyingCurrency()
          .equals(other.getBuyingCurrency());
      result = result && (getChannelManagerId()
          == other.getChannelManagerId());
      result = result && (getChannelTypeId()
          == other.getChannelTypeId());
      result = result && (getContractStatusId()
          == other.getContractStatusId());
      result = result && (getContractTypeId()
          == other.getContractTypeId());
      result = result && (getFollowOnContractId()
          == other.getFollowOnContractId());
      result = result && (getNoEndDates()
          == other.getNoEndDates());
      result = result && getStayFrom()
          .equals(other.getStayFrom());
      result = result && getStayTo()
          .equals(other.getStayTo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROPERTYID_FIELD_NUMBER;
      hash = (53 * hash) + getPropertyId();
      hash = (37 * hash) + CONTRACTID_FIELD_NUMBER;
      hash = (53 * hash) + getContractId();
      hash = (37 * hash) + BOOKINGFROM_FIELD_NUMBER;
      hash = (53 * hash) + getBookingFrom().hashCode();
      hash = (37 * hash) + BOOKING_TO_FIELD_NUMBER;
      hash = (53 * hash) + getBookingTo().hashCode();
      hash = (37 * hash) + BUYING_CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getBuyingCurrency().hashCode();
      hash = (37 * hash) + CHANNEL_MANAGER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelManagerId();
      hash = (37 * hash) + CHANNEL_TYPE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelTypeId();
      hash = (37 * hash) + CONTRACT_STATUS_ID_FIELD_NUMBER;
      hash = (53 * hash) + getContractStatusId();
      hash = (37 * hash) + CONTRACT_TYPE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getContractTypeId();
      hash = (37 * hash) + FOLLOW_ON_CONTRACT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFollowOnContractId();
      hash = (37 * hash) + NO_END_DATES_FIELD_NUMBER;
      hash = (53 * hash) + getNoEndDates();
      hash = (37 * hash) + STAY_FROM_FIELD_NUMBER;
      hash = (53 * hash) + getStayFrom().hashCode();
      hash = (37 * hash) + STAY_TO_FIELD_NUMBER;
      hash = (53 * hash) + getStayTo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jac.travels.protobuf.Contract.ContractRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jac.travels.protobuf.Contract.ContractRequestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jac.travels.protobuf.ContractRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jac.travels.protobuf.ContractRequestProto)
        com.jac.travels.protobuf.Contract.ContractRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jac.travels.protobuf.Contract.internal_static_com_jac_travels_protobuf_ContractRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jac.travels.protobuf.Contract.internal_static_com_jac_travels_protobuf_ContractRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jac.travels.protobuf.Contract.ContractRequestProto.class, com.jac.travels.protobuf.Contract.ContractRequestProto.Builder.class);
      }

      // Construct using com.jac.travels.protobuf.Contract.ContractRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        propertyId_ = 0;

        contractId_ = 0;

        bookingFrom_ = "";

        bookingTo_ = "";

        buyingCurrency_ = "";

        channelManagerId_ = 0;

        channelTypeId_ = 0;

        contractStatusId_ = 0;

        contractTypeId_ = 0;

        followOnContractId_ = 0;

        noEndDates_ = 0;

        stayFrom_ = "";

        stayTo_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jac.travels.protobuf.Contract.internal_static_com_jac_travels_protobuf_ContractRequestProto_descriptor;
      }

      public com.jac.travels.protobuf.Contract.ContractRequestProto getDefaultInstanceForType() {
        return com.jac.travels.protobuf.Contract.ContractRequestProto.getDefaultInstance();
      }

      public com.jac.travels.protobuf.Contract.ContractRequestProto build() {
        com.jac.travels.protobuf.Contract.ContractRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jac.travels.protobuf.Contract.ContractRequestProto buildPartial() {
        com.jac.travels.protobuf.Contract.ContractRequestProto result = new com.jac.travels.protobuf.Contract.ContractRequestProto(this);
        result.propertyId_ = propertyId_;
        result.contractId_ = contractId_;
        result.bookingFrom_ = bookingFrom_;
        result.bookingTo_ = bookingTo_;
        result.buyingCurrency_ = buyingCurrency_;
        result.channelManagerId_ = channelManagerId_;
        result.channelTypeId_ = channelTypeId_;
        result.contractStatusId_ = contractStatusId_;
        result.contractTypeId_ = contractTypeId_;
        result.followOnContractId_ = followOnContractId_;
        result.noEndDates_ = noEndDates_;
        result.stayFrom_ = stayFrom_;
        result.stayTo_ = stayTo_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jac.travels.protobuf.Contract.ContractRequestProto) {
          return mergeFrom((com.jac.travels.protobuf.Contract.ContractRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jac.travels.protobuf.Contract.ContractRequestProto other) {
        if (other == com.jac.travels.protobuf.Contract.ContractRequestProto.getDefaultInstance()) return this;
        if (other.getPropertyId() != 0) {
          setPropertyId(other.getPropertyId());
        }
        if (other.getContractId() != 0) {
          setContractId(other.getContractId());
        }
        if (!other.getBookingFrom().isEmpty()) {
          bookingFrom_ = other.bookingFrom_;
          onChanged();
        }
        if (!other.getBookingTo().isEmpty()) {
          bookingTo_ = other.bookingTo_;
          onChanged();
        }
        if (!other.getBuyingCurrency().isEmpty()) {
          buyingCurrency_ = other.buyingCurrency_;
          onChanged();
        }
        if (other.getChannelManagerId() != 0) {
          setChannelManagerId(other.getChannelManagerId());
        }
        if (other.getChannelTypeId() != 0) {
          setChannelTypeId(other.getChannelTypeId());
        }
        if (other.getContractStatusId() != 0) {
          setContractStatusId(other.getContractStatusId());
        }
        if (other.getContractTypeId() != 0) {
          setContractTypeId(other.getContractTypeId());
        }
        if (other.getFollowOnContractId() != 0) {
          setFollowOnContractId(other.getFollowOnContractId());
        }
        if (other.getNoEndDates() != 0) {
          setNoEndDates(other.getNoEndDates());
        }
        if (!other.getStayFrom().isEmpty()) {
          stayFrom_ = other.stayFrom_;
          onChanged();
        }
        if (!other.getStayTo().isEmpty()) {
          stayTo_ = other.stayTo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jac.travels.protobuf.Contract.ContractRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jac.travels.protobuf.Contract.ContractRequestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int propertyId_ ;
      /**
       * <code>int32 propertyId = 10;</code>
       */
      public int getPropertyId() {
        return propertyId_;
      }
      /**
       * <code>int32 propertyId = 10;</code>
       */
      public Builder setPropertyId(int value) {
        
        propertyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 propertyId = 10;</code>
       */
      public Builder clearPropertyId() {
        
        propertyId_ = 0;
        onChanged();
        return this;
      }

      private int contractId_ ;
      /**
       * <code>int32 contractId = 20;</code>
       */
      public int getContractId() {
        return contractId_;
      }
      /**
       * <code>int32 contractId = 20;</code>
       */
      public Builder setContractId(int value) {
        
        contractId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contractId = 20;</code>
       */
      public Builder clearContractId() {
        
        contractId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bookingFrom_ = "";
      /**
       * <code>string bookingFrom = 30;</code>
       */
      public java.lang.String getBookingFrom() {
        java.lang.Object ref = bookingFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bookingFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bookingFrom = 30;</code>
       */
      public com.google.protobuf.ByteString
          getBookingFromBytes() {
        java.lang.Object ref = bookingFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookingFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bookingFrom = 30;</code>
       */
      public Builder setBookingFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bookingFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bookingFrom = 30;</code>
       */
      public Builder clearBookingFrom() {
        
        bookingFrom_ = getDefaultInstance().getBookingFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string bookingFrom = 30;</code>
       */
      public Builder setBookingFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bookingFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bookingTo_ = "";
      /**
       * <code>string booking_to = 40;</code>
       */
      public java.lang.String getBookingTo() {
        java.lang.Object ref = bookingTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bookingTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string booking_to = 40;</code>
       */
      public com.google.protobuf.ByteString
          getBookingToBytes() {
        java.lang.Object ref = bookingTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookingTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string booking_to = 40;</code>
       */
      public Builder setBookingTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bookingTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string booking_to = 40;</code>
       */
      public Builder clearBookingTo() {
        
        bookingTo_ = getDefaultInstance().getBookingTo();
        onChanged();
        return this;
      }
      /**
       * <code>string booking_to = 40;</code>
       */
      public Builder setBookingToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bookingTo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object buyingCurrency_ = "";
      /**
       * <code>string buying_currency = 50;</code>
       */
      public java.lang.String getBuyingCurrency() {
        java.lang.Object ref = buyingCurrency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buyingCurrency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string buying_currency = 50;</code>
       */
      public com.google.protobuf.ByteString
          getBuyingCurrencyBytes() {
        java.lang.Object ref = buyingCurrency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buyingCurrency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string buying_currency = 50;</code>
       */
      public Builder setBuyingCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buyingCurrency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string buying_currency = 50;</code>
       */
      public Builder clearBuyingCurrency() {
        
        buyingCurrency_ = getDefaultInstance().getBuyingCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>string buying_currency = 50;</code>
       */
      public Builder setBuyingCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buyingCurrency_ = value;
        onChanged();
        return this;
      }

      private int channelManagerId_ ;
      /**
       * <code>int32 channel_manager_id = 60;</code>
       */
      public int getChannelManagerId() {
        return channelManagerId_;
      }
      /**
       * <code>int32 channel_manager_id = 60;</code>
       */
      public Builder setChannelManagerId(int value) {
        
        channelManagerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 channel_manager_id = 60;</code>
       */
      public Builder clearChannelManagerId() {
        
        channelManagerId_ = 0;
        onChanged();
        return this;
      }

      private int channelTypeId_ ;
      /**
       * <code>int32 channel_type_id = 70;</code>
       */
      public int getChannelTypeId() {
        return channelTypeId_;
      }
      /**
       * <code>int32 channel_type_id = 70;</code>
       */
      public Builder setChannelTypeId(int value) {
        
        channelTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 channel_type_id = 70;</code>
       */
      public Builder clearChannelTypeId() {
        
        channelTypeId_ = 0;
        onChanged();
        return this;
      }

      private int contractStatusId_ ;
      /**
       * <code>int32 contract_status_id = 80;</code>
       */
      public int getContractStatusId() {
        return contractStatusId_;
      }
      /**
       * <code>int32 contract_status_id = 80;</code>
       */
      public Builder setContractStatusId(int value) {
        
        contractStatusId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contract_status_id = 80;</code>
       */
      public Builder clearContractStatusId() {
        
        contractStatusId_ = 0;
        onChanged();
        return this;
      }

      private int contractTypeId_ ;
      /**
       * <code>int32 contract_type_id = 90;</code>
       */
      public int getContractTypeId() {
        return contractTypeId_;
      }
      /**
       * <code>int32 contract_type_id = 90;</code>
       */
      public Builder setContractTypeId(int value) {
        
        contractTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contract_type_id = 90;</code>
       */
      public Builder clearContractTypeId() {
        
        contractTypeId_ = 0;
        onChanged();
        return this;
      }

      private int followOnContractId_ ;
      /**
       * <code>int32 follow_on_contract_id = 100;</code>
       */
      public int getFollowOnContractId() {
        return followOnContractId_;
      }
      /**
       * <code>int32 follow_on_contract_id = 100;</code>
       */
      public Builder setFollowOnContractId(int value) {
        
        followOnContractId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 follow_on_contract_id = 100;</code>
       */
      public Builder clearFollowOnContractId() {
        
        followOnContractId_ = 0;
        onChanged();
        return this;
      }

      private int noEndDates_ ;
      /**
       * <code>int32 no_end_dates = 110;</code>
       */
      public int getNoEndDates() {
        return noEndDates_;
      }
      /**
       * <code>int32 no_end_dates = 110;</code>
       */
      public Builder setNoEndDates(int value) {
        
        noEndDates_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 no_end_dates = 110;</code>
       */
      public Builder clearNoEndDates() {
        
        noEndDates_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object stayFrom_ = "";
      /**
       * <code>string stay_from = 120;</code>
       */
      public java.lang.String getStayFrom() {
        java.lang.Object ref = stayFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stayFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stay_from = 120;</code>
       */
      public com.google.protobuf.ByteString
          getStayFromBytes() {
        java.lang.Object ref = stayFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stayFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stay_from = 120;</code>
       */
      public Builder setStayFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stayFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stay_from = 120;</code>
       */
      public Builder clearStayFrom() {
        
        stayFrom_ = getDefaultInstance().getStayFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string stay_from = 120;</code>
       */
      public Builder setStayFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stayFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stayTo_ = "";
      /**
       * <code>string stay_to = 130;</code>
       */
      public java.lang.String getStayTo() {
        java.lang.Object ref = stayTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stayTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stay_to = 130;</code>
       */
      public com.google.protobuf.ByteString
          getStayToBytes() {
        java.lang.Object ref = stayTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stayTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stay_to = 130;</code>
       */
      public Builder setStayTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stayTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stay_to = 130;</code>
       */
      public Builder clearStayTo() {
        
        stayTo_ = getDefaultInstance().getStayTo();
        onChanged();
        return this;
      }
      /**
       * <code>string stay_to = 130;</code>
       */
      public Builder setStayToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stayTo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jac.travels.protobuf.ContractRequestProto)
    }

    // @@protoc_insertion_point(class_scope:com.jac.travels.protobuf.ContractRequestProto)
    private static final com.jac.travels.protobuf.Contract.ContractRequestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jac.travels.protobuf.Contract.ContractRequestProto();
    }

    public static com.jac.travels.protobuf.Contract.ContractRequestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContractRequestProto>
        PARSER = new com.google.protobuf.AbstractParser<ContractRequestProto>() {
      public ContractRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContractRequestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContractRequestProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContractRequestProto> getParserForType() {
      return PARSER;
    }

    public com.jac.travels.protobuf.Contract.ContractRequestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jac_travels_protobuf_ContractRequestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jac_travels_protobuf_ContractRequestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030resources/contract.proto\022\030com.jac.trav" +
      "els.protobuf\"\305\002\n\024ContractRequestProto\022\022\n" +
      "\npropertyId\030\n \001(\005\022\022\n\ncontractId\030\024 \001(\005\022\023\n" +
      "\013bookingFrom\030\036 \001(\t\022\022\n\nbooking_to\030( \001(\t\022\027" +
      "\n\017buying_currency\0302 \001(\t\022\032\n\022channel_manag" +
      "er_id\030< \001(\005\022\027\n\017channel_type_id\030F \001(\005\022\032\n\022" +
      "contract_status_id\030P \001(\005\022\030\n\020contract_typ" +
      "e_id\030Z \001(\005\022\035\n\025follow_on_contract_id\030d \001(" +
      "\005\022\024\n\014no_end_dates\030n \001(\005\022\021\n\tstay_from\030x \001" +
      "(\t\022\020\n\007stay_to\030\202\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jac_travels_protobuf_ContractRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jac_travels_protobuf_ContractRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jac_travels_protobuf_ContractRequestProto_descriptor,
        new java.lang.String[] { "PropertyId", "ContractId", "BookingFrom", "BookingTo", "BuyingCurrency", "ChannelManagerId", "ChannelTypeId", "ContractStatusId", "ContractTypeId", "FollowOnContractId", "NoEndDates", "StayFrom", "StayTo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
