// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/property.proto

package com.jac.travels.protobuf;

public final class Property {
  private Property() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PropertyRequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jac.travels.protobuf.PropertyRequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 propertyId = 10;</code>
     */
    int getPropertyId();

    /**
     * <code>int32 cutOffTime = 20;</code>
     */
    int getCutOffTime();

    /**
     * <code>string name = 30;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 30;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>float starRating = 40;</code>
     */
    float getStarRating();

    /**
     * <code>int32 status = 50;</code>
     */
    int getStatus();

    /**
     * <code>string timeZoneId = 60;</code>
     */
    java.lang.String getTimeZoneId();
    /**
     * <code>string timeZoneId = 60;</code>
     */
    com.google.protobuf.ByteString
        getTimeZoneIdBytes();
  }
  /**
   * Protobuf type {@code com.jac.travels.protobuf.PropertyRequestProto}
   */
  public  static final class PropertyRequestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jac.travels.protobuf.PropertyRequestProto)
      PropertyRequestProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PropertyRequestProto.newBuilder() to construct.
    private PropertyRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PropertyRequestProto() {
      propertyId_ = 0;
      cutOffTime_ = 0;
      name_ = "";
      starRating_ = 0F;
      status_ = 0;
      timeZoneId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PropertyRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 80: {

              propertyId_ = input.readInt32();
              break;
            }
            case 160: {

              cutOffTime_ = input.readInt32();
              break;
            }
            case 242: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 325: {

              starRating_ = input.readFloat();
              break;
            }
            case 400: {

              status_ = input.readInt32();
              break;
            }
            case 482: {
              java.lang.String s = input.readStringRequireUtf8();

              timeZoneId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jac.travels.protobuf.Property.internal_static_com_jac_travels_protobuf_PropertyRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jac.travels.protobuf.Property.internal_static_com_jac_travels_protobuf_PropertyRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jac.travels.protobuf.Property.PropertyRequestProto.class, com.jac.travels.protobuf.Property.PropertyRequestProto.Builder.class);
    }

    public static final int PROPERTYID_FIELD_NUMBER = 10;
    private int propertyId_;
    /**
     * <code>int32 propertyId = 10;</code>
     */
    public int getPropertyId() {
      return propertyId_;
    }

    public static final int CUTOFFTIME_FIELD_NUMBER = 20;
    private int cutOffTime_;
    /**
     * <code>int32 cutOffTime = 20;</code>
     */
    public int getCutOffTime() {
      return cutOffTime_;
    }

    public static final int NAME_FIELD_NUMBER = 30;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 30;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 30;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARRATING_FIELD_NUMBER = 40;
    private float starRating_;
    /**
     * <code>float starRating = 40;</code>
     */
    public float getStarRating() {
      return starRating_;
    }

    public static final int STATUS_FIELD_NUMBER = 50;
    private int status_;
    /**
     * <code>int32 status = 50;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int TIMEZONEID_FIELD_NUMBER = 60;
    private volatile java.lang.Object timeZoneId_;
    /**
     * <code>string timeZoneId = 60;</code>
     */
    public java.lang.String getTimeZoneId() {
      java.lang.Object ref = timeZoneId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeZoneId_ = s;
        return s;
      }
    }
    /**
     * <code>string timeZoneId = 60;</code>
     */
    public com.google.protobuf.ByteString
        getTimeZoneIdBytes() {
      java.lang.Object ref = timeZoneId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeZoneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (propertyId_ != 0) {
        output.writeInt32(10, propertyId_);
      }
      if (cutOffTime_ != 0) {
        output.writeInt32(20, cutOffTime_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 30, name_);
      }
      if (starRating_ != 0F) {
        output.writeFloat(40, starRating_);
      }
      if (status_ != 0) {
        output.writeInt32(50, status_);
      }
      if (!getTimeZoneIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 60, timeZoneId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (propertyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, propertyId_);
      }
      if (cutOffTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, cutOffTime_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(30, name_);
      }
      if (starRating_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(40, starRating_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(50, status_);
      }
      if (!getTimeZoneIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(60, timeZoneId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jac.travels.protobuf.Property.PropertyRequestProto)) {
        return super.equals(obj);
      }
      com.jac.travels.protobuf.Property.PropertyRequestProto other = (com.jac.travels.protobuf.Property.PropertyRequestProto) obj;

      boolean result = true;
      result = result && (getPropertyId()
          == other.getPropertyId());
      result = result && (getCutOffTime()
          == other.getCutOffTime());
      result = result && getName()
          .equals(other.getName());
      result = result && (
          java.lang.Float.floatToIntBits(getStarRating())
          == java.lang.Float.floatToIntBits(
              other.getStarRating()));
      result = result && (getStatus()
          == other.getStatus());
      result = result && getTimeZoneId()
          .equals(other.getTimeZoneId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROPERTYID_FIELD_NUMBER;
      hash = (53 * hash) + getPropertyId();
      hash = (37 * hash) + CUTOFFTIME_FIELD_NUMBER;
      hash = (53 * hash) + getCutOffTime();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STARRATING_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStarRating());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + TIMEZONEID_FIELD_NUMBER;
      hash = (53 * hash) + getTimeZoneId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jac.travels.protobuf.Property.PropertyRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jac.travels.protobuf.Property.PropertyRequestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jac.travels.protobuf.PropertyRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jac.travels.protobuf.PropertyRequestProto)
        com.jac.travels.protobuf.Property.PropertyRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jac.travels.protobuf.Property.internal_static_com_jac_travels_protobuf_PropertyRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jac.travels.protobuf.Property.internal_static_com_jac_travels_protobuf_PropertyRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jac.travels.protobuf.Property.PropertyRequestProto.class, com.jac.travels.protobuf.Property.PropertyRequestProto.Builder.class);
      }

      // Construct using com.jac.travels.protobuf.Property.PropertyRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        propertyId_ = 0;

        cutOffTime_ = 0;

        name_ = "";

        starRating_ = 0F;

        status_ = 0;

        timeZoneId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jac.travels.protobuf.Property.internal_static_com_jac_travels_protobuf_PropertyRequestProto_descriptor;
      }

      public com.jac.travels.protobuf.Property.PropertyRequestProto getDefaultInstanceForType() {
        return com.jac.travels.protobuf.Property.PropertyRequestProto.getDefaultInstance();
      }

      public com.jac.travels.protobuf.Property.PropertyRequestProto build() {
        com.jac.travels.protobuf.Property.PropertyRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jac.travels.protobuf.Property.PropertyRequestProto buildPartial() {
        com.jac.travels.protobuf.Property.PropertyRequestProto result = new com.jac.travels.protobuf.Property.PropertyRequestProto(this);
        result.propertyId_ = propertyId_;
        result.cutOffTime_ = cutOffTime_;
        result.name_ = name_;
        result.starRating_ = starRating_;
        result.status_ = status_;
        result.timeZoneId_ = timeZoneId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jac.travels.protobuf.Property.PropertyRequestProto) {
          return mergeFrom((com.jac.travels.protobuf.Property.PropertyRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jac.travels.protobuf.Property.PropertyRequestProto other) {
        if (other == com.jac.travels.protobuf.Property.PropertyRequestProto.getDefaultInstance()) return this;
        if (other.getPropertyId() != 0) {
          setPropertyId(other.getPropertyId());
        }
        if (other.getCutOffTime() != 0) {
          setCutOffTime(other.getCutOffTime());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getStarRating() != 0F) {
          setStarRating(other.getStarRating());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getTimeZoneId().isEmpty()) {
          timeZoneId_ = other.timeZoneId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jac.travels.protobuf.Property.PropertyRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jac.travels.protobuf.Property.PropertyRequestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int propertyId_ ;
      /**
       * <code>int32 propertyId = 10;</code>
       */
      public int getPropertyId() {
        return propertyId_;
      }
      /**
       * <code>int32 propertyId = 10;</code>
       */
      public Builder setPropertyId(int value) {
        
        propertyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 propertyId = 10;</code>
       */
      public Builder clearPropertyId() {
        
        propertyId_ = 0;
        onChanged();
        return this;
      }

      private int cutOffTime_ ;
      /**
       * <code>int32 cutOffTime = 20;</code>
       */
      public int getCutOffTime() {
        return cutOffTime_;
      }
      /**
       * <code>int32 cutOffTime = 20;</code>
       */
      public Builder setCutOffTime(int value) {
        
        cutOffTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cutOffTime = 20;</code>
       */
      public Builder clearCutOffTime() {
        
        cutOffTime_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 30;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 30;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 30;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 30;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 30;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private float starRating_ ;
      /**
       * <code>float starRating = 40;</code>
       */
      public float getStarRating() {
        return starRating_;
      }
      /**
       * <code>float starRating = 40;</code>
       */
      public Builder setStarRating(float value) {
        
        starRating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float starRating = 40;</code>
       */
      public Builder clearStarRating() {
        
        starRating_ = 0F;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 50;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 50;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 50;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object timeZoneId_ = "";
      /**
       * <code>string timeZoneId = 60;</code>
       */
      public java.lang.String getTimeZoneId() {
        java.lang.Object ref = timeZoneId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeZoneId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timeZoneId = 60;</code>
       */
      public com.google.protobuf.ByteString
          getTimeZoneIdBytes() {
        java.lang.Object ref = timeZoneId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeZoneId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timeZoneId = 60;</code>
       */
      public Builder setTimeZoneId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timeZoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timeZoneId = 60;</code>
       */
      public Builder clearTimeZoneId() {
        
        timeZoneId_ = getDefaultInstance().getTimeZoneId();
        onChanged();
        return this;
      }
      /**
       * <code>string timeZoneId = 60;</code>
       */
      public Builder setTimeZoneIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timeZoneId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jac.travels.protobuf.PropertyRequestProto)
    }

    // @@protoc_insertion_point(class_scope:com.jac.travels.protobuf.PropertyRequestProto)
    private static final com.jac.travels.protobuf.Property.PropertyRequestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jac.travels.protobuf.Property.PropertyRequestProto();
    }

    public static com.jac.travels.protobuf.Property.PropertyRequestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PropertyRequestProto>
        PARSER = new com.google.protobuf.AbstractParser<PropertyRequestProto>() {
      public PropertyRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PropertyRequestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PropertyRequestProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PropertyRequestProto> getParserForType() {
      return PARSER;
    }

    public com.jac.travels.protobuf.Property.PropertyRequestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jac_travels_protobuf_PropertyRequestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jac_travels_protobuf_PropertyRequestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030resources/property.proto\022\030com.jac.trav" +
      "els.protobuf\"\204\001\n\024PropertyRequestProto\022\022\n" +
      "\npropertyId\030\n \001(\005\022\022\n\ncutOffTime\030\024 \001(\005\022\014\n" +
      "\004name\030\036 \001(\t\022\022\n\nstarRating\030( \001(\002\022\016\n\006statu" +
      "s\0302 \001(\005\022\022\n\ntimeZoneId\030< \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jac_travels_protobuf_PropertyRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jac_travels_protobuf_PropertyRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jac_travels_protobuf_PropertyRequestProto_descriptor,
        new java.lang.String[] { "PropertyId", "CutOffTime", "Name", "StarRating", "Status", "TimeZoneId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
